### ISSUE TITLE
Beklentiler

### ISSUE THREAD

**Issue by aliyilmaz** [RKursatV/afad-toplanma-alani-acik-veri#1]
Merhaba, öncelikle böyle bir projeyi başlattığın için seni kutlarım. Şu an hala daha internette bu konuya ilişkin sağlıklı bir veri yığını yok. Eğer projeyi geliştirmeyi sürdürmek niyetindeysen benim projeden beklentilerim aşağıdaki gibidir.

* E-devlet'e erişimi genel olarak sağlıklı çalışıyor, bazen limit aşma ve ana bilgisayar bağlantıyı sonlandırdı uyarılarıyla karşılaştım fakat bunun e-devlet tarafından kaynaklı olduğu çok açıktı ama bu konuda da bir iyileştirme belki uygulanabilir
* Paylaştığın JSON dosyaları dışında, bir il veya illerin toplanma alanlarını istedim, şanlıurfa ve rize'nin bilgilerini ekledi
* E-devlette varsayılan olarak gelen bir mahalledeki maksimum toplanma alanı sayısı 3 adet, bunu tamamını kapsayacak şekilde düzenlemek gerekiyor
* E-devletten gelen koordinat verileri, enlem,boylam söz diziminde olması gerekirken, boylam,enlem şeklinde, bunu düzeltecek bir fonksiyonun yazılması gerekiyor
* Poligonal yapıda bulunan toplanma alanı parsellerinin orta noktasını tespit eden bir fonksiyonun yazılarak tespit edilen bu koordinat noktasının konum başlığında tutulması gerekiyor
* Aşağıdaki veritabanı yapısına sahip bir mysql tablosuna tüm illerin verilerinin eklenmesi ve söz konusu veritabanının yedeğinin proje sayfasına eklenmesi gerekiyor

tablo yapısı
```php
- id
- tesis_adi // REYHANLI KUŞAKLI MAHALLESİ İLKOKUL BAHÇESİ TOPLANMA ALANI",
- il_adi // HATAY
- ilce_adi // REYHANLI
- mahalle_adi // KUŞAKLI
- sokak_adi // 6317.
- acik_adres // KUŞAKLI MAHALLESİ
- konum // 36.67477487619327, 36.28320757330296
- polygon // [poligonal json verisi]
- tabela_kod // 3110-030-01
- created_at
- updated_at
```

**Comment by RKursatV** [comment]
Merhaba, projeye olan ilginiz için teşekkürler. Proje afet döneminde geliştirilen yazılımları desteklemek amaçlı ortaya çıkmıştı ve misyonunu tamamladı. İhtiyaçlarınız halihazırda bulunan kodların manipülasyonuyla karşılanabilir gözüküyor, fakat benim için bu projeyi sürdürmenin bir anlamı bulunmuyor.

**Comment by aliyilmaz** [comment]
> Merhaba, projeye olan ilginiz için teşekkürler. Proje afet döneminde geliştirilen yazılımları desteklemek amaçlı ortaya çıkmıştı ve misyonunu tamamladı. İhtiyaçlarınız halihazırda bulunan kodların manipülasyonuyla karşılanabilir gözüküyor, fakat benim için bu projeyi sürdürmenin bir anlamı bulunmuyor.

Anladım. Zaman ayırdığınız için teşekkür ederim.
